services:
  db:
    image: postgres:16-alpine
    container_name: lab_emt_db
    environment:
      POSTGRES_DB: lab1_emt
      POSTGRES_USER: saramihajlova
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saramihajlova -d lab1_emt"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./lab_emt
      dockerfile: Dockerfile
    container_name: lab_emt_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab1_emt
      SPRING_DATASOURCE_USERNAME: saramihajlova
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Accommodation-ui
      dockerfile: Dockerfile
    container_name: accommodation_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
