apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: lab-emt
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres123"
  JWT_SECRET: "NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA=="
