apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: lab-emt
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/lab1_emt"
  SPRING_DATASOURCE_USERNAME: "saramihajlova"
